app:
  title: APAC Geo-Coverage Tool
  favicon: assets/plana.png
source:
  filename: 'Dataset.xlsx'
  sheet:
    region:
      name: Region Vertical Overview
    dealer:
      name: Dealer List
    keyAccount:
      name: Key Account List
vertical:
  - F&B
  - Heavy Industry
  - Chemical/Pharma
  - Electronics
  - Mobility
showOptionalData:
  projectedRevenue: False
tiers:
  - name: Elite
    color: orange
  - name: Certified
    color: lightgray
  - name: Authorized
    color: blue
  - name: Probation
    color: black
isCustomer:
  - value: True
    color: green
  - value: False
    color: red
