app:
  title: APAC Interactive Factory Map
  favicon: assets/plana.png
source:
  filename: 'Dataset.xlsx'
  sheet:
    region:
      name: Region Vertical Overview
      addOthers: True
      addTotal: True
    partner:
      name: Partner List
    keyAccount:
      name: Key Account List
data:
  currency: USD
vertical:
  - F&B
  - Heavy Industry
  - Chemical/Pharma
  - Electronics
  - Mobility
tiers:
  - name: Elite
    color: orange
  - name: Certified
    color: darkgreen
  - name: Authorized
    color: cadetblue
  - name: Probation
    color: lightgray
